# See: https://github.com/rust-lang/rust/issues/59302
[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=-crt-static"
]

# See: https://github.com/rust-lang/rust/issues/59302
[target.aarch64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=-crt-static"
]
